In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("../Instant_datasets/11_data.csv")

In [10]:
df

,id,latter,gyroX,gyroY,gyroZ,accelX,accelY,accelZ,UserID
0,5220,A,-0.022550,0.036438,-0.058438,-0.109105,0.541576,0.848715,11
1,5221,T,-0.005500,0.136537,0.103537,0.007755,0.530150,0.842077,11
2,5222,F,-0.067237,0.169537,0.093912,-0.034874,0.571648,0.800778,11
3,5223,A,0.186312,0.011962,0.020488,-0.192420,0.544528,0.856761,11
4,5224,R,0.006325,0.288888,-0.034925,-0.023968,0.590416,0.822299,11
...,...,...,...,...,...,...,...,...,...
645,6515,W,0.032038,-0.096250,0.011962,-0.007847,0.683919,0.733477,11
646,6516,A,-0.010588,-0.196350,0.021588,-0.051287,0.685662,0.730020,11
647,6517,B,-0.059538,-0.181500,0.016225,-0.006317,0.676577,0.704629,11
648,6518,U,-0.103262,-0.195250,-0.024200,-0.008566,0.693203,0.716560,11
649,6519,S,0.083187,-0.154825,-0.010312,-0.016321,0.675154,0.751021,11

First in first we neet to create our test data respect to latters

In [11]:
#seperate data frame respect to latter,
latter_set = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
a_df = df[df["latter"] == "A"]
# learn data_length
num_row = len(a_df)

In [14]:
a_df.iloc[0]

,id,latter,gyroX,gyroY,gyroZ,accelX,accelY,accelZ,UserID
0,5220,A,-0.022550,0.036438,-0.058438,-0.109105,0.541576,0.848715,11
3,5223,A,0.186312,0.011962,0.020488,-0.192420,0.544528,0.856761,11
29,5275,A,0.018150,-0.142450,0.014025,-0.115024,0.546976,0.785176,11
35,5281,A,0.095837,-0.041250,0.006600,-0.127154,0.570638,0.775907,11
68,5340,A,-0.041525,-0.022138,-0.025438,-0.156735,0.600710,0.819653,11
143,5545,A,0.004262,-0.020762,0.019250,-0.053734,0.683919,0.790790,11
160,5614,A,-0.081675,-0.075763,0.037538,-0.160605,0.489051,0.841572,11
171,5625,A,0.048400,-0.187550,0.004537,-0.093304,0.501593,0.886954,11
178,5632,A,-0.031487,-0.004262,-0.019938,-0.083714,0.503230,0.869716,11
194,5674,A,-0.085800,-0.100237,-0.064763,-0.131849,0.607241,0.757139,11
202,5682,A,-0.114537,-0.016088,-0.031762,-0.097388,0.626315,0.804250,11
211,5743,A,-0.029288,-0.024612,-0.038087,-0.085243,0.554517,0.858198,11
313,5845,A,0.137087,0.094600,0.006600,-0.070773,0.620701,0.795685,11
347,6009,A,-0.157850,-0.096937,0.006600,-0.057818,0.504760,0.854527,11
365,6053,A,0.025300,0.069300,-0.081813,-0.040993,0.519138,0.797107,11
371,6059,A,0.052938,0.053350,0.024612,-0.030484,0.574814,0.795486,11
378,6066,A,0.021038,0.075625,0.042762,-0.027333,0.583579,0.845962,11
471,6263,A,-0.095837,-0.094187,-0.023100,-0.018554,0.381675,0.922838,11
486,6278,A,-0.173662,0.040013,0.012100,-0.034675,0.409513,0.902648,11
496,6288,A,0.021312,-0.008938,0.065312,0.006730,0.400443,0.895306,11
497,6289,A,-0.026538,-0.033550,-0.050738,-0.028037,0.387793,0.905309,11
510,6302,A,-0.028738,-0.289162,-0.047575,-0.049359,0.436342,0.898977,11
512,6304,A,-0.084013,0.048538,-0.012375,-0.058843,0.394324,0.905309,11
529,6321,A,-0.142725,-0.090750,-0.066688,-0.029261,0.876033,0.561354,11
573,6365,A,-0.074525,-0.136537,0.014162,-0.059347,0.621925,0.708805,11
610,6428,A,-0.064900,-0.185762,0.011000,-0.100539,0.648738,0.779578,11
646,6516,A,-0.010588,-0.196350,0.021588,-0.051287,0.685662,0.730020,11

In [12]:
chunk_size = 5
chunks = [a_df.iloc[i:i+chunk_size] for i in range(0, len(a_df), chunk_size)]

# YalnÄ±zca 5 satÄ±rlÄ± olan alt DataFrame'leri seÃ§elim
chunks = [chunk for chunk in chunks if len(chunk) == chunk_size]

chunks[0]

,id,latter,gyroX,gyroY,gyroZ,accelX,accelY,accelZ,UserID
0,5220,A,-0.022550,0.036438,-0.058438,-0.109105,0.541576,0.848715,11
3,5223,A,0.186312,0.011962,0.020488,-0.192420,0.544528,0.856761,11
29,5275,A,0.018150,-0.142450,0.014025,-0.115024,0.546976,0.785176,11
35,5281,A,0.095837,-0.041250,0.006600,-0.127154,0.570638,0.775907,11
68,5340,A,-0.041525,-0.022138,-0.025438,-0.156735,0.600710,0.819653,11

In [13]:
import pandas as pd

# column_keys listesini tanÄ±mlayÄ±n
column_keys = [
    "gyroX_mean", "gyroY_mean", "gyroZ_mean",
    "accelX_mean", "accelY_mean", "accelZ_mean",
    "gyroX_std", "gyroY_std", "gyroZ_std",
    "accelX_std", "accelY_std", "accelZ_std",
    "target_column"
]

# SÃ¼tun adlarÄ±yla uyumlu olarak boÅŸ bir DataFrame oluÅŸturun
feature_df = pd.DataFrame(columns=column_keys)

# OluÅŸturulan DataFrame'i ekrana yazdÄ±rÄ±n
print(feature_df)

# chunks dÃ¶ngÃ¼sÃ¼ baÅŸlamadan Ã¶nce tanÄ±mlanmÄ±ÅŸ olmalÄ±dÄ±r
for i, chunk in enumerate(chunks, start=1):
    # Her bir alt DataFrame iÃ§in istatistiksel Ã¶zellikleri hesaplayÄ±n
    mean_values = chunk[['gyroX', 'gyroY', 'gyroZ', 'accelX', 'accelY', 'accelZ']].mean()
    std_values = chunk[['gyroX', 'gyroY', 'gyroZ', 'accelX', 'accelY', 'accelZ']].std()

    # Yeni satÄ±r verilerini oluÅŸturun
    new_row_data = {
        "gyroX_mean": mean_values["gyroX"],
        "gyroY_mean": mean_values["gyroY"],
        "gyroZ_mean": mean_values["gyroZ"],
        "accelX_mean": mean_values["accelX"],
        "accelY_mean": mean_values["accelY"],
        "accelZ_mean": mean_values["accelZ"],
        "gyroX_std": std_values["gyroX"],
        "gyroY_std": std_values["gyroY"],
        "gyroZ_std": std_values["gyroZ"],
        "accelX_std": std_values["accelX"],
        "accelY_std": std_values["accelY"],
        "accelZ_std": std_values["accelZ"],
        "target_column": df.iloc[1, 1]  # Burada df yerine chunk kullanmanÄ±z gerekebilir
    }

    # Yeni satÄ±rÄ± DataFrame'e ekleyin
    feature_df = pd.concat([feature_df, pd.DataFrame([new_row_data])], ignore_index=True)

Empty DataFrame
Columns: [gyroX_mean, gyroY_mean, gyroZ_mean, accelX_mean, accelY_mean, accelZ_mean, gyroX_std, gyroY_std, gyroZ_std, accelX_std, accelY_std, accelZ_std, target_column]
Index: []

/var/folders/8n/k4zvj6rn6zj1pjxj58pv87100000gn/T/ipykernel_86118/1769415102.py:42: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  feature_df = pd.concat([feature_df, pd.DataFrame([new_row_data])], ignore_index=True)

In [ ]:
feature_df

,gyroX_mean,gyroY_mean,gyroZ_mean,accelX_mean,accelY_mean,accelZ_mean,gyroX_std,gyroY_std,gyroZ_std,accelX_std,accelY_std,accelZ_std,target_column
0,0.047245,-0.031488,-0.008553,-0.140088,0.560886,0.817242,0.093940,0.068915,0.033001,0.034537,0.025075,0.036383,T
1,-0.029260,-0.077715,-0.004675,-0.104641,0.557007,0.829234,0.057236,0.072825,0.039631,0.041923,0.085456,0.054310,T
2,-0.027858,0.005252,-0.027692,-0.070443,0.565086,0.821953,0.116668,0.077258,0.036761,0.022203,0.056357,0.031605,T
3,-0.034842,0.013173,0.024337,-0.020863,0.470005,0.872448,0.096141,0.067546,0.033236,0.016522,0.100230,0.051474,T
4,-0.071308,-0.100292,-0.032643,-0.044969,0.543283,0.795951,0.047668,0.126176,0.032829,0.015427,0.208991,0.155855,T