In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

C:\Users\cukad\AppData\Local\Temp\ipykernel_9156\2151744951.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv("./Data/Instant_datasets/11_data.csv")

In [3]:
df

,id,latter,gyroX,gyroY,gyroZ,accelX,accelY,accelZ,UserID
0,5220,A,-0.022550,0.036438,-0.058438,-0.109105,0.541576,0.848715,11
1,5221,T,-0.005500,0.136537,0.103537,0.007755,0.530150,0.842077,11
2,5222,F,-0.067237,0.169537,0.093912,-0.034874,0.571648,0.800778,11
3,5223,A,0.186312,0.011962,0.020488,-0.192420,0.544528,0.856761,11
4,5224,R,0.006325,0.288888,-0.034925,-0.023968,0.590416,0.822299,11
...,...,...,...,...,...,...,...,...,...
645,6515,W,0.032038,-0.096250,0.011962,-0.007847,0.683919,0.733477,11
646,6516,A,-0.010588,-0.196350,0.021588,-0.051287,0.685662,0.730020,11
647,6517,B,-0.059538,-0.181500,0.016225,-0.006317,0.676577,0.704629,11
648,6518,U,-0.103262,-0.195250,-0.024200,-0.008566,0.693203,0.716560,11
649,6519,S,0.083187,-0.154825,-0.010312,-0.016321,0.675154,0.751021,11

First in first we neet to create our test data respect to latters

In [6]:
#seperate data frame respect to latter,
latter_set = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
a_df = df[df["latter"] == "A"]
# learn data_length
num_row = len(a_df)

In [56]:
chunk_size = 5
chunks = [a_df.iloc[i:i+chunk_size] for i in range(0, len(a_df), chunk_size)]

# YalnÄ±zca 5 satÄ±rlÄ± olan alt DataFrame'leri seÃ§elim
chunks = [chunk for chunk in chunks if len(chunk) == chunk_size]

chunks[0]

,id,latter,gyroX,gyroY,gyroZ,accelX,accelY,accelZ,UserID
0,5220,A,-0.022550,0.036438,-0.058438,-0.109105,0.541576,0.848715,11
3,5223,A,0.186312,0.011962,0.020488,-0.192420,0.544528,0.856761,11
29,5275,A,0.018150,-0.142450,0.014025,-0.115024,0.546976,0.785176,11
35,5281,A,0.095837,-0.041250,0.006600,-0.127154,0.570638,0.775907,11
68,5340,A,-0.041525,-0.022138,-0.025438,-0.156735,0.600710,0.819653,11

In [88]:
import pandas as pd

# column_keys listesini tanÄ±mlayÄ±n
column_keys = [
    "gyroX_mean", "gyroY_mean", "gyroZ_mean",
    "accelX_mean", "accelY_mean", "accelZ_mean",
    "gyroX_std", "gyroY_std", "gyroZ_std",
    "accelX_std", "accelY_std", "accelZ_std",
    "target_column"
]

# SÃ¼tun adlarÄ±yla uyumlu olarak boÅŸ bir DataFrame oluÅŸturun
feature_df = pd.DataFrame(columns=column_keys)

# OluÅŸturulan DataFrame'i ekrana yazdÄ±rÄ±n
print(feature_df)

# chunks dÃ¶ngÃ¼sÃ¼ baÅŸlamadan Ã¶nce tanÄ±mlanmÄ±ÅŸ olmalÄ±dÄ±r
for i, chunk in enumerate(chunks, start=1):
    # Her bir alt DataFrame iÃ§in istatistiksel Ã¶zellikleri hesaplayÄ±n
    mean_values = chunk[['gyroX', 'gyroY', 'gyroZ', 'accelX', 'accelY', 'accelZ']].mean()
    std_values = chunk[['gyroX', 'gyroY', 'gyroZ', 'accelX', 'accelY', 'accelZ']].std()

    # Yeni satÄ±r verilerini oluÅŸturun
    new_row_data = {
        "gyroX_mean": mean_values["gyroX"],
        "gyroY_mean": mean_values["gyroY"],
        "gyroZ_mean": mean_values["gyroZ"],
        "accelX_mean": mean_values["accelX"],
        "accelY_mean": mean_values["accelY"],
        "accelZ_mean": mean_values["accelZ"],
        "gyroX_std": std_values["gyroX"],
        "gyroY_std": std_values["gyroY"],
        "gyroZ_std": std_values["gyroZ"],
        "accelX_std": std_values["accelX"],
        "accelY_std": std_values["accelY"],
        "accelZ_std": std_values["accelZ"],
        "target_column": df.iloc[1, 1]  # Burada df yerine chunk kullanmanÄ±z gerekebilir
    }

    # Yeni satÄ±rÄ± DataFrame'e ekleyin
    feature_df = pd.concat([feature_df, pd.DataFrame([new_row_data])], ignore_index=True)

Empty DataFrame
Columns: [gyroX_mean, gyroY_mean, gyroZ_mean, accelX_mean, accelY_mean, accelZ_mean, gyroX_std, gyroY_std, gyroZ_std, accelX_std, accelY_std, accelZ_std, target_column]
Index: []

C:\Users\cukad\AppData\Local\Temp\ipykernel_9156\1769415102.py:42: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  feature_df = pd.concat([feature_df, pd.DataFrame([new_row_data])], ignore_index=True)

In [89]:
feature_df

,gyroX_mean,gyroY_mean,gyroZ_mean,accelX_mean,accelY_mean,accelZ_mean,gyroX_std,gyroY_std,gyroZ_std,accelX_std,accelY_std,accelZ_std,target_column
0,0.047245,-0.031488,-0.008553,-0.140088,0.560886,0.817242,0.093940,0.068915,0.033001,0.034537,0.025075,0.036383,T
1,-0.029260,-0.077715,-0.004675,-0.104641,0.557007,0.829234,0.057236,0.072825,0.039631,0.041923,0.085456,0.054310,T
2,-0.027858,0.005252,-0.027692,-0.070443,0.565086,0.821953,0.116668,0.077258,0.036761,0.022203,0.056357,0.031605,T
3,-0.034842,0.013173,0.024337,-0.020863,0.470005,0.872448,0.096141,0.067546,0.033236,0.016522,0.100230,0.051474,T
4,-0.071308,-0.100292,-0.032643,-0.044969,0.543283,0.795951,0.047668,0.126176,0.032829,0.015427,0.208991,0.155855,T